import { decodeGoalControl, type StrategyFilters } from "@shared/goalStrategy";
import { toNumber } from "./gold";

export type GoalTrade = { id?: number; tradeDate: Date | string | number; pnl: number | string | null; result: string; risk?: number | string | null; reward?: number | string | null; patienceScore?: number | null; setupQuality?: string | null; hasScreenshot?: boolean; mistake?: string | null; session?: string | null; timeframe?: string | null; level?: string | null };
export type GoalPlan = { planDate: Date | string | number; overallRating?: number | null };
export type TraderGoal = { id: number; name: string; description?: string | null; period: "DAILY" | "WEEKLY" | "MONTHLY"; metric: string; comparison: "GTE" | "LTE"; target: string | number; active: boolean; notify?: boolean; isCustom?: boolean };
export type TraderGoalStatus = "PENDING" | "IN_PROGRESS" | "MET" | "SAFE" | "AT_RISK" | "BREACHED";

const keyFormatter = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit" });
function dayKey(value: Date | string | number) { const parts = keyFormatter.formatToParts(new Date(value)); const get = (type: string) => parts.find(part => part.type === type)?.value ?? "00"; return `${get("year")}-${get("month")}-${get("day")}`; }
function calendarDate(key: string) { const [year, month, day] = key.split("-").map(Number); return new Date(Date.UTC(year, month - 1, day)); }
function shiftKey(key: string, days: number) { const date = calendarDate(key); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function periodStart(period: TraderGoal["period"], now: Date) { const today = dayKey(now); if (period === "DAILY") return today; if (period === "MONTHLY") return `${today.slice(0, 8)}01`; const date = calendarDate(today); const offset = (date.getUTCDay() + 6) % 7; return shiftKey(today, -offset); }
function maxDrawdown(rows: GoalTrade[]) { let equity = 0; let peak = 0; let worst = 0; for (const row of rows) { equity += toNumber(row.pnl); peak = Math.max(peak, equity); worst = Math.max(worst, peak - equity); } return worst; }
function currentLossStreak(rows: GoalTrade[]) { let streak = 0; for (const row of [...rows].reverse()) { if (row.result !== "LOSS") break; streak += 1; } return streak; }
function tokens(value?: string | null) { return (value ?? "").toLowerCase().split(/[|,;/]+/).map(token => token.trim()).filter(Boolean); }
function hasBehavior(row: GoalTrade, behavior: "fomo" | "revenge" | "overtrading" | "oversize" | "rule_break") { const tags = tokens(row.mistake); const aliases: Record<typeof behavior, string[]> = { fomo: ["fomo", "chase", "chased"], revenge: ["revenge", "recover loss", "breakeven chase"], overtrading: ["overtrading", "overtrade", "too many trades"], oversize: ["oversize", "over-risked", "over risk"], rule_break: ["early entry", "late entry", "moved sl", "closed early", "fomo", "revenge", "overtrading", "overtrade", "oversize", "over-risked"] };
  return tags.some(tag => aliases[behavior].some(alias => tag.includes(alias)));
}
function hasBehaviorBreach(row: GoalTrade) { return ["fomo", "revenge", "overtrading", "oversize"].some(behavior => hasBehavior(row, behavior as "fomo" | "revenge" | "overtrading" | "oversize")); }
function matchesScope(row: GoalTrade, scope: StrategyFilters) { const level = scope.level?.toLowerCase() || ""; return (!scope.session || row.session === scope.session) && (!scope.timeframe || row.timeframe === scope.timeframe) && (!level || tokens(row.level).some(item => item === level)) && (!scope.setupQuality || row.setupQuality === scope.setupQuality); }
function scopeLabel(scope: StrategyFilters) { return [scope.session, scope.timeframe, scope.level, scope.setupQuality].filter(Boolean).join(" · ") || "All strategy contexts"; }

export function goalCategory(metric: string) { return ["daily_loss", "weekly_drawdown", "trade_count", "consecutive_losses"].includes(metric) ? "CAPITAL SAFETY" : ["behavior_breaches", "fomo_trades", "revenge_trades", "overtrading_trades", "oversize_trades", "rule_breaks", "screenshot_rate", "session_plan_rate", "weekly_reviews", "process_quality", "minimum_sample", "strategy_compliance"].includes(metric) ? "EXECUTION DISCIPLINE" : "PERFORMANCE"; }
export function goalMetricLabel(metric: string) { return ({ daily_loss: "Max daily loss", weekly_drawdown: "Max weekly drawdown", trade_count: "Max trades", consecutive_losses: "Loss streak", behavior_breaches: "Behavior breaches", fomo_trades: "FOMO entries", revenge_trades: "Revenge entries", overtrading_trades: "Overtrades", oversize_trades: "Oversized entries", rule_breaks: "Rule breaks", screenshot_rate: "Evidence rate", session_plan_rate: "Session-plan coverage", weekly_reviews: "Weekly reviews", process_quality: "Process-quality average", minimum_sample: "Closed-trade sample", strategy_compliance: "Strategy compliance", net_pnl: "Net P&L", win_rate: "Win rate", avg_rr: "Average planned R:R", profit_factor: "Profit factor", avg_patience: "Patience average", quality_setup: "A / A+ setup rate", risk_defined_rate: "Risk-defined trade rate" } as Record<string, string>)[metric] ?? metric; }
export function goalAction(metric: string) { return ({ daily_loss: "Stop for the day and protect tomorrow’s capital.", weekly_drawdown: "Reduce risk and review the week before the next session.", consecutive_losses: "Take the configured reset before any new entry.", trade_count: "No more entries; wait for the next review window.", behavior_breaches: "Pause discretionary entries; review the tagged trade and return only when the written trigger is present.", fomo_trades: "Stop chasing price; wait for your written trigger.", revenge_trades: "Step away and reset after the loss rather than recover it.", overtrading_trades: "Close the platform after the planned number of attempts.", oversize_trades: "Return to normal size before the next valid setup.", rule_breaks: "Review the broken rule and do not add another discretionary entry.", screenshot_rate: "Capture the setup before or immediately after every entry.", session_plan_rate: "Save a same-session protocol before relying on the review.", weekly_reviews: "Complete the execution review before the next week.", process_quality: "Complete the scorecard honestly, then write one process improvement.", minimum_sample: "Do not change the strategy from a few outcomes; build the configured closed-trade sample first.", strategy_compliance: "Only trade your configured session, setup, and execution context.", risk_defined_rate: "Define planned dollar risk before judging the setup.", avg_rr: "Only take setups whose planned reward justifies the defined risk.", quality_setup: "Wait for the setup-quality standard in your written plan." } as Record<string, string>)[metric] ?? "Review the control against your written strategy."; }
export function formatGoalValue(metric: string, value: number) { if (["daily_loss", "weekly_drawdown", "net_pnl"].includes(metric)) return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 }).format(value); if (["win_rate", "quality_setup", "screenshot_rate", "session_plan_rate", "risk_defined_rate", "strategy_compliance"].includes(metric)) return `${value.toFixed(1)}%`; if (["avg_rr", "profit_factor"].includes(metric)) return value.toFixed(2); return metric === "avg_patience" || metric === "process_quality" ? `${value.toFixed(1)} / 5` : String(Math.round(value)); }

export function assessTraderGoal(goal: TraderGoal, trades: GoalTrade[], plans: GoalPlan[] = [], now = new Date()) {
  const start = periodStart(goal.period, now); const today = dayKey(now);
  const periodRows = trades.filter(row => { const key = dayKey(row.tradeDate); return row.result !== "OPEN" && key >= start && key <= today; }).sort((a, b) => new Date(a.tradeDate).getTime() - new Date(b.tradeDate).getTime());
  const config = decodeGoalControl(goal.description); const rows = periodRows.filter(row => matchesScope(row, config.strategy)); const periodPlans = plans.filter(plan => { const key = dayKey(plan.planDate); return key >= start && key <= today; }); const relevantPlans = periodPlans.filter(plan => plan.overallRating != null); const plannedDays = new Set(periodPlans.map(plan => dayKey(plan.planDate)));
  const wins = rows.filter(row => row.result === "WIN"); const netPnl = rows.reduce((sum, row) => sum + toNumber(row.pnl), 0); const grossProfit = wins.reduce((sum, row) => sum + Math.max(0, toNumber(row.pnl)), 0); const grossLoss = Math.abs(rows.reduce((sum, row) => sum + Math.min(0, toNumber(row.pnl)), 0));
  const cleanScopeTrades = periodRows.filter(row => matchesScope(row, config.strategy) && !hasBehavior(row, "rule_break"));
  const values: Record<string, number> = {
    trade_count: rows.length, daily_loss: Math.min(0, netPnl), weekly_drawdown: -maxDrawdown(rows), consecutive_losses: currentLossStreak(rows),
    behavior_breaches: rows.filter(hasBehaviorBreach).length, fomo_trades: rows.filter(row => hasBehavior(row, "fomo")).length, revenge_trades: rows.filter(row => hasBehavior(row, "revenge")).length, overtrading_trades: rows.filter(row => hasBehavior(row, "overtrading")).length, oversize_trades: rows.filter(row => hasBehavior(row, "oversize")).length, rule_breaks: rows.filter(row => hasBehavior(row, "rule_break")).length,
    screenshot_rate: rows.length ? rows.filter(row => Boolean(row.hasScreenshot)).length / rows.length * 100 : 0, session_plan_rate: rows.length ? rows.filter(row => plannedDays.has(dayKey(row.tradeDate))).length / rows.length * 100 : 0, weekly_reviews: relevantPlans.length, process_quality: relevantPlans.length ? relevantPlans.reduce((sum, plan) => sum + toNumber(plan.overallRating), 0) / relevantPlans.length : 0, minimum_sample: rows.length, strategy_compliance: periodRows.length ? cleanScopeTrades.length / periodRows.length * 100 : 0,
    net_pnl: netPnl, win_rate: rows.length ? wins.length / rows.length * 100 : 0, avg_rr: rows.length ? rows.reduce((sum, row) => sum + (toNumber(row.risk) > 0 ? toNumber(row.reward) / toNumber(row.risk) : 0), 0) / rows.length : 0, risk_defined_rate: rows.length ? rows.filter(row => toNumber(row.risk) > 0).length / rows.length * 100 : 0, profit_factor: grossLoss ? grossProfit / grossLoss : grossProfit ? 99 : 0, avg_patience: rows.length ? rows.reduce((sum, row) => sum + toNumber(row.patienceScore), 0) / rows.length : 0, quality_setup: rows.length ? rows.filter(row => row.setupQuality === "A" || row.setupQuality === "A+").length / rows.length * 100 : 0,
  };
  const value = values[goal.metric] ?? 0; const rawTarget = toNumber(goal.target); const isLossFloor = ["daily_loss", "weekly_drawdown"].includes(goal.metric); const target = isLossFloor ? -Math.abs(rawTarget) : rawTarget; const hasActivity = periodRows.length > 0 || periodPlans.length > 0; const usage = isLossFloor ? Math.min(100, Math.abs(value) / Math.max(1, Math.abs(target)) * 100) : target > 0 ? Math.min(100, Math.abs(value) / target * 100) : value > 0 ? 100 : 0; let status: TraderGoalStatus = "PENDING";
  if (hasActivity && goal.comparison === "GTE") status = value >= target ? "MET" : "IN_PROGRESS";
  if (hasActivity && isLossFloor) status = value < target ? "BREACHED" : value <= target * 0.8 ? "AT_RISK" : "SAFE";
  else if (hasActivity && goal.comparison === "LTE") status = target === 0 ? value > 0 ? "BREACHED" : "SAFE" : value > target ? "BREACHED" : value >= target * 0.8 ? "AT_RISK" : "SAFE";
  const remaining = isLossFloor ? Math.max(0, value - target) : goal.comparison === "GTE" ? Math.max(0, target - value) : Math.max(0, target - value); const periodLabel = goal.period === "DAILY" ? "today (PKT)" : goal.period === "WEEKLY" ? "this week (PKT)" : "this month (PKT)";
  return { goal, config, value, target, rows: rows.length, periodRows: periodRows.length, hasActivity, status, percentage: usage, remaining, periodLabel, category: goalCategory(goal.metric), metricLabel: goalMetricLabel(goal.metric), action: goalAction(goal.metric), scopeLabel: scopeLabel(config.strategy), current: formatGoalValue(goal.metric, value), targetLabel: formatGoalValue(goal.metric, target), remainingLabel: formatGoalValue(goal.metric, remaining) };
}
