import { supabase, hasSupabase } from './supabase';
import type { CashMovement, DailyPlan, GoalMetric, MentorReport, MissedTrade, Mt5Connection, Notification, OptionCatalog, OptionList, Profile, Trade, TradingAccount, TradingRule, TraderGoal } from './types';
import { sessionForDate } from './time';

const STORE_KEY = 'gold-journal-local-v2';
type LocalDb = { profile: Profile | null; accounts: TradingAccount[]; trades: Trade[]; missed: MissedTrade[]; plans: DailyPlan[]; goals: TraderGoal[]; notifications: Notification[]; options: OptionList[]; rules: TradingRule[]; connections: Mt5Connection[]; reports: MentorReport[]; cash: CashMovement[] };
const blankDb = (): LocalDb => ({ profile: null, accounts: [], trades: [], missed: [], plans: [], goals: [], notifications: [], options: [], rules: [], connections: [], reports: [], cash: [] });
function readDb(): LocalDb { try { return { ...blankDb(), ...(JSON.parse(localStorage.getItem(STORE_KEY) || '{}')) }; } catch { return blankDb(); } }
function writeDb(db: LocalDb) { localStorage.setItem(STORE_KEY, JSON.stringify(db)); }
const uid = () => crypto.randomUUID();
async function query<T>(table: string, accountId: string) { if (!supabase) return null; const { data, error } = await supabase.from(table).select('*').eq('account_id', accountId).order('created_at', { ascending: false }); if (error) throw error; return (data || []) as T[]; }
async function write<T extends object>(table: string, value: any) { if (!supabase) return { ...(value as object), id: uid(), created_at: new Date().toISOString(), updated_at: new Date().toISOString() } as unknown as T & { id: string }; const { data, error } = await supabase.from(table).insert(value).select().single(); if (error) throw error; return data as T & { id: string }; }
async function update<T extends object>(table: string, id: string, value: Partial<T>) { if (!supabase) return null; const { data, error } = await supabase.from(table).update(value as any).eq('id', id).select().single(); if (error) throw error; return data as T; }
async function remove(table: string, id: string) { if (supabase) { const { error } = await supabase.from(table).delete().eq('id', id); if (error) throw error; } }

export function localMode() { return !hasSupabase; }
export async function getSessionUser() { if (supabase) { const { data } = await supabase.auth.getUser(); return data.user; } return { id: 'local-trader', email: 'local@example.com' } as { id: string; email: string } ; }
export async function signIn(email: string, password: string) { if (!supabase) return { user: { id: 'local-trader', email } }; const { data, error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw new Error('Unable to sign in with those credentials.'); return data; }
export async function signUp(email: string, password: string) { if (!supabase) return { user: { id: 'local-trader', email } }; const { data, error } = await supabase.auth.signUp({ email, password }); if (error) throw new Error('Unable to create this account.'); return data; }
export async function signOut() { if (supabase) await supabase.auth.signOut(); }
export function subscribeAuth(callback: (user: { id: string; email?: string } | null) => void) { if (!supabase) { callback({ id: 'local-trader', email: 'local@example.com' }); return () => undefined; } const { data } = supabase.auth.onAuthStateChange((_event, session) => callback(session?.user ? { id: session.user.id, email: session.user.email } : null)); return () => data.subscription.unsubscribe(); }

export async function loadWorkspace(accountId: string) {
  if (!supabase) { const db = readDb(); return { trades: db.trades.filter(x => x.account_id === accountId), missed: db.missed.filter(x => x.account_id === accountId), plans: db.plans.filter(x => x.account_id === accountId), goals: db.goals.filter(x => x.account_id === accountId), notifications: db.notifications.filter(x => x.account_id === accountId), options: db.options.filter(x => x.account_id === accountId), rules: db.rules.filter(x => x.account_id === accountId), connections: db.connections.filter(x => x.account_id === accountId), reports: db.reports.filter(x => x.account_id === accountId), cash: db.cash.filter(x => x.account_id === accountId) }; }
  const [trades, missed, plans, goals, notifications, options, rules, connections, reports, cash] = await Promise.all([query<Trade>('trades', accountId), query<MissedTrade>('skipped_trades', accountId), query<DailyPlan>('daily_plans', accountId), query<TraderGoal>('trader_goals', accountId), query<Notification>('notifications', accountId), query<OptionList>('option_lists', accountId), query<TradingRule>('trading_rules', accountId), query<Mt5Connection>('mt5_connections', accountId), query<MentorReport>('mentor_reports', accountId), query<CashMovement>('cash_movements', accountId)]);
  return { trades: trades || [], missed: missed || [], plans: plans || [], goals: goals || [], notifications: notifications || [], options: options || [], rules: rules || [], connections: connections || [], reports: reports || [], cash: cash || [] };
}
export async function getAccounts(userId: string) { if (!supabase) { const db = readDb(); if (!db.accounts.length) { const account = { id: uid(), owner_id: userId, name: 'Main Account', broker_name: null, base_currency: 'USD', starting_balance: null, is_active: true, is_archived: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }; db.accounts = [account]; writeDb(db); } return db.accounts.filter(x => !x.is_archived); } const { data, error } = await supabase.from('trading_accounts').select('*').eq('is_archived', false).order('created_at'); if (error) throw error; return (data || []) as TradingAccount[]; }
export async function createAccount(userId: string, name: string) { const value = { owner_id: userId, name, broker_name: null, base_currency: 'USD', starting_balance: null, is_active: true, is_archived: false }; if (supabase) return write<TradingAccount>('trading_accounts', value); const db = readDb(); const item = { ...value, id: uid(), created_at: new Date().toISOString(), updated_at: new Date().toISOString() } as TradingAccount; db.accounts.push(item); writeDb(db); return item; }
export async function updateAccount(id: string, value: Partial<TradingAccount>) { if (supabase) return update<TradingAccount>('trading_accounts', id, value); const db = readDb(); const item = db.accounts.find(x => x.id === id); if (item) Object.assign(item, value, { updated_at: new Date().toISOString() }); writeDb(db); return item; }
export async function removeAccount(id: string) { if (supabase) return update<TradingAccount>('trading_accounts', id, { is_archived: true }); const db = readDb(); db.accounts = db.accounts.filter(x => x.id !== id); writeDb(db); }

function localAdd<T extends { account_id: string }>(key: keyof LocalDb, value: Omit<T, 'id' | 'created_at' | 'updated_at'> | Omit<T, 'id'>): T { const db = readDb(); const item = { ...value, id: uid(), created_at: new Date().toISOString(), updated_at: new Date().toISOString() } as unknown as T; (db[key] as unknown as T[]).push(item); writeDb(db); return item; }
export async function addTrade(value: Omit<Trade, 'id' | 'created_at' | 'updated_at'>) { return supabase ? write<Trade>('trades', value) : localAdd<Trade>('trades', value as any); }
export async function editTrade(id: string, value: Partial<Trade>) { if (supabase) return update<Trade>('trades', id, value); const db = readDb(); const item = db.trades.find(x => x.id === id); if (item) Object.assign(item, value, { updated_at: new Date().toISOString() }); writeDb(db); return item; }
export async function deleteTrade(id: string) { return supabase ? remove('trades', id) : (() => { const db = readDb(); db.trades = db.trades.filter(x => x.id !== id); writeDb(db); })(); }
export async function addMissed(value: Omit<MissedTrade, 'id' | 'created_at' | 'updated_at'>) { return supabase ? write<MissedTrade>('skipped_trades', value) : localAdd<MissedTrade>('missed', value as any); }
export async function addPlan(value: Omit<DailyPlan, 'id' | 'created_at' | 'updated_at'>) { return supabase ? write<DailyPlan>('daily_plans', value) : localAdd<DailyPlan>('plans', value as any); }
export async function editPlan(id: string, value: Partial<DailyPlan>) { if (supabase) return update<DailyPlan>('daily_plans', id, value); const db = readDb(); const item = db.plans.find(x => x.id === id); if (item) Object.assign(item, value, { updated_at: new Date().toISOString() }); writeDb(db); return item; }
export async function addGoal(value: Omit<TraderGoal, 'id' | 'created_at' | 'updated_at'>) { return supabase ? write<TraderGoal>('trader_goals', value) : localAdd<TraderGoal>('goals', value as any); }
export async function editGoal(id: string, value: Partial<TraderGoal>) { if (supabase) return update<TraderGoal>('trader_goals', id, value); const db = readDb(); const item = db.goals.find(x => x.id === id); if (item) Object.assign(item, value, { updated_at: new Date().toISOString() }); writeDb(db); return item; }
export async function deleteGoal(id: string) { return supabase ? remove('trader_goals', id) : (() => { const db = readDb(); db.goals = db.goals.filter(x => x.id !== id); writeDb(db); })(); }
export async function addOption(value: Omit<OptionList, 'id' | 'created_at' | 'updated_at'>) { return supabase ? write<OptionList>('option_lists', value) : localAdd<OptionList>('options', value as any); }
export async function editOption(id: string, value: Partial<OptionList>) { if (supabase) return update<OptionList>('option_lists', id, value); const db = readDb(); const item = db.options.find(x => x.id === id); if (item) Object.assign(item, value, { updated_at: new Date().toISOString() }); writeDb(db); return item; }
export async function deleteOption(id: string) { return supabase ? remove('option_lists', id) : (() => { const db = readDb(); db.options = db.options.filter(x => x.id !== id); writeDb(db); })(); }
export async function addRule(value: Omit<TradingRule, 'id' | 'created_at' | 'updated_at'>) { return supabase ? write<TradingRule>('trading_rules', value) : localAdd<TradingRule>('rules', value as any); }
export async function editRule(id: string, value: Partial<TradingRule>) { if (supabase) return update<TradingRule>('trading_rules', id, value); const db = readDb(); const item = db.rules.find(x => x.id === id); if (item) Object.assign(item, value, { updated_at: new Date().toISOString() }); writeDb(db); return item; }
export async function deleteRule(id: string) { return supabase ? remove('trading_rules', id) : (() => { const db = readDb(); db.rules = db.rules.filter(x => x.id !== id); writeDb(db); })(); }
export async function addCash(value: Omit<CashMovement, 'id'>) { return supabase ? write<CashMovement>('cash_movements', value) : localAdd<CashMovement>('cash', value as any); }
export async function addReport(value: Omit<MentorReport, 'id' | 'created_at'>) { return supabase ? write<MentorReport>('mentor_reports', value) : localAdd<MentorReport>('reports', value as any); }

export function catalog(options: OptionList[]): OptionCatalog { const map: Record<string, keyof OptionCatalog> = { level: 'levels', timeframe: 'timeframes', setup_quality: 'setupQualities', execution_type: 'executionTypes', market_condition: 'marketConditions', confirmation: 'confirmations', sl: 'slPlacements', tp: 'tpPlacements', emotion: 'emotions', behavior: 'behaviorTags', bias: 'biases', reason: 'reasons', confidence: 'confidence' }; const out: OptionCatalog = { levels: [], timeframes: [], setupQualities: [], executionTypes: [], marketConditions: [], confirmations: [], slPlacements: [], tpPlacements: [], emotions: [], behaviorTags: [], biases: [], reasons: [], confidence: [] }; options.filter(x => x.enabled).sort((a, b) => a.sort_order - b.sort_order).forEach(x => { const key = map[x.category]; if (key && !out[key].includes(x.label)) out[key].push(x.label); }); return out; }
export const defaultOptions: Array<[string, string]> = [['level', 'Asia high'], ['level', 'London open'], ['level', 'Previous day high'], ['timeframe', '5m'], ['timeframe', '15m'], ['timeframe', '1h'], ['setup_quality', 'A setup'], ['setup_quality', 'B setup'], ['execution_type', 'Breakout'], ['execution_type', 'Retest'], ['market_condition', 'Trending'], ['market_condition', 'Range'], ['confirmation', 'Structure break'], ['confirmation', 'Liquidity sweep'], ['sl', 'Beyond structure'], ['tp', 'Next liquidity'], ['emotion', 'Calm'], ['emotion', 'FOMO'], ['emotion', 'Frustrated'], ['behavior', 'Overtrading'], ['behavior', 'Revenge trading'], ['behavior', 'FOMO'], ['bias', 'Bullish'], ['bias', 'Bearish'], ['reason', 'No confirmation'], ['reason', 'Risk too high'], ['confidence', 'Low'], ['confidence', 'Medium'], ['confidence', 'High']];
export async function ensureDefaults(accountId: string) { if (supabase) { const { count } = await supabase.from('option_lists').select('*', { count: 'exact', head: true }).eq('account_id', accountId); if (!count) await supabase.from('option_lists').insert(defaultOptions.map(([category, label], i) => ({ account_id: accountId, category, label, enabled: true, sort_order: i }))); const { count: rc } = await supabase.from('trading_rules').select('*', { count: 'exact', head: true }).eq('account_id', accountId); if (!rc) await supabase.from('trading_rules').insert([{ account_id: accountId, title: 'Only trade my planned session', is_active: true, sort_order: 0 }, { account_id: accountId, title: 'Risk is defined before entry', is_active: true, sort_order: 1 }]); return; } const db = readDb(); if (!db.options.some(x => x.account_id === accountId)) { db.options.push(...defaultOptions.map(([category, label], i) => ({ id: uid(), account_id: accountId, category, label, enabled: true, sort_order: i, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }))); } if (!db.rules.some(x => x.account_id === accountId)) db.rules.push({ id: uid(), account_id: accountId, title: 'Only trade my planned session', is_active: true, sort_order: 0, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }, { id: uid(), account_id: accountId, title: 'Risk is defined before entry', is_active: true, sort_order: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }); writeDb(db); }
