import { z } from 'zod';

const safeText = (max = 2000) => z.string().trim().min(1).max(max).refine((v) => !/[<>\u0000-\u001F]/.test(v), 'Text contains unsafe characters');
const nullableText = (max = 500) => z.string().trim().min(1).max(max).refine((v) => !/[<>\u0000-\u001F]/.test(v), 'Text contains unsafe characters').nullable().optional();
export const directionSchema = z.enum(['Long', 'Short']);
export const resultSchema = z.enum(['Win', 'Loss', 'Breakeven', 'Open']);
export const tradeSchema = z.object({ trade_at_utc: z.string().datetime(), pkt_session: z.string().min(1), direction: directionSchema, result: resultSchema, source: z.enum(['manual', 'mt5']).default('manual'), risk_usd: z.number().positive().max(1000000), planned_reward_usd: z.number().nonnegative().max(10000000).nullable(), realized_pnl: z.number().max(10000000).nullable(), bias: nullableText(), level: nullableText(), timeframe: nullableText(100), setup_quality: nullableText(100), execution_type: nullableText(100), market_condition: nullableText(100), confirmation_type: nullableText(100), sl_placement: nullableText(100), tp_placement: nullableText(100), behavior_tags: z.array(safeText(80)).max(30), hold_quality: z.number().int().min(1).max(5).nullable().optional(), patience_score: z.number().int().min(1).max(5).nullable().optional(), emotion_before: nullableText(80), emotion_during: nullableText(80), emotion_after: nullableText(80), notes: nullableText(4000) });
export const skippedTradeSchema = z.object({ skipped_at: z.string().datetime(), pkt_session: z.string().min(1), direction: directionSchema, reason: safeText(120), confidence: safeText(80), later_outcome: resultSchema, estimated_missed_pnl: z.number().max(10000000).nullable(), notes: nullableText(4000) });
export const goalSchema = z.object({ title: safeText(120), period: z.enum(['daily', 'weekly', 'monthly']), metric: z.enum(['realized_pnl', 'loss_streak', 'trade_count', 'rule_violations', 'fomo_tags', 'revenge_tags', 'screenshot_rate', 'plan_completion']), comparator: z.enum(['at_most', 'at_least']), target: z.number().finite(), strategy_scope: nullableText(120), is_active: z.boolean(), notification_enabled: z.boolean(), template_key: nullableText(80) });
export const planSchema = z.object({ plan_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), pre_market_plan: nullableText(4000), thesis: nullableText(4000), key_levels: nullableText(2000), scenarios: nullableText(4000), invalidation: nullableText(2000), news_context: nullableText(2000), risk_limits: nullableText(2000), selected_rules: z.array(safeText(120)).max(30), execution_checklist: z.record(z.boolean()), post_session_score: z.number().int().min(1).max(10).nullable(), review_notes: nullableText(4000), is_archived: z.boolean() });
export const optionSchema = z.object({ category: safeText(60), label: safeText(100), enabled: z.boolean(), sort_order: z.number().int().min(0).max(10000) });
export const goalTemplate = { max_daily_loss: { title: 'Max daily loss', metric: 'realized_pnl' as const, comparator: 'at_most' as const, target: -100 }, max_weekly_loss: { title: 'Max weekly loss', metric: 'realized_pnl' as const, comparator: 'at_most' as const, target: -300 }, trade_frequency: { title: 'Daily trade frequency', metric: 'trade_count' as const, comparator: 'at_most' as const, target: 5 }, required_plan: { title: 'Complete the daily plan', metric: 'plan_completion' as const, comparator: 'at_least' as const, target: 1 } };
