import { sql } from "drizzle-orm";
import { bigint, boolean, check, integer, jsonb, numeric, pgTable, serial, text, timestamp, uniqueIndex, index, foreignKey, varchar, primaryKey } from "drizzle-orm/pg-core";

export const rateLimitBuckets = pgTable("gj_rate_limit_buckets", {
  scope: varchar("scope", { length: 80 }).notNull(), identityHash: varchar("identityHash", { length: 128 }).notNull(), windowStartedAt: timestamp("windowStartedAt", { withTimezone: true }).notNull(), count: integer("count").default(0).notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [primaryKey({ columns: [table.scope, table.identityHash], name: "gj_rate_limit_buckets_pk" })]);

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  openId: varchar("openId", { length: 128 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: varchar("role", { length: 16 }).default("user").notNull(),
  createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn", { withTimezone: true }).defaultNow().notNull(),
}, table => [check("gj_users_role_valid", sql`"role" in ('user', 'admin')`)]);

export const accounts = pgTable("gj_accounts", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), name: varchar("name", { length: 100 }).notNull(), bootstrapKey: varchar("bootstrapKey", { length: 32 }), startingBalance: numeric("startingBalance", { precision: 14, scale: 2 }).default("0.00").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_accounts_user_idx").on(table.userId), index("gj_accounts_user_created_idx").on(table.userId, table.createdAt.desc()), uniqueIndex("gj_accounts_user_bootstrap_unique").on(table.userId, table.bootstrapKey), uniqueIndex("gj_accounts_id_user_unique").on(table.id, table.userId), check("gj_accounts_starting_balance_nonnegative", sql`"startingBalance" >= 0`)]);

export const trades = pgTable("gj_trades", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), tradeDate: timestamp("tradeDate", { withTimezone: true }).notNull(), session: varchar("session", { length: 40 }).notNull(), direction: varchar("direction", { length: 8 }).notNull(), result: varchar("result", { length: 16 }).notNull(), level: varchar("level", { length: 100 }).default(""), timeframe: varchar("timeframe", { length: 20 }).default(""), setupQuality: varchar("setupQuality", { length: 40 }).default(""), executionType: varchar("executionType", { length: 80 }).default(""), marketCondition: varchar("marketCondition", { length: 40 }).default(""), biasAlignment: varchar("biasAlignment", { length: 40 }).default(""), confirmationType: varchar("confirmationType", { length: 60 }).default(""), slPlacement: varchar("slPlacement", { length: 60 }).default(""), tpPlacement: varchar("tpPlacement", { length: 60 }).default(""), mistake: varchar("mistake", { length: 80 }).default(""), holdQuality: varchar("holdQuality", { length: 60 }).default(""), patienceScore: integer("patienceScore"), risk: numeric("risk", { precision: 14, scale: 2 }), reward: numeric("reward", { precision: 14, scale: 2 }), pnl: numeric("pnl", { precision: 14, scale: 2 }).default("0.00").notNull(), openTime: timestamp("openTime", { withTimezone: true }), closeTime: timestamp("closeTime", { withTimezone: true }), mfe: numeric("mfe", { precision: 14, scale: 2 }), mae: numeric("mae", { precision: 14, scale: 2 }), notes: text("notes"), emotionBefore: text("emotionBefore"), emotionDuring: text("emotionDuring"), emotionAfter: text("emotionAfter"), screenshotKey: varchar("screenshotKey", { length: 500 }), screenshotName: varchar("screenshotName", { length: 255 }), mt5Ticket: bigint("mt5Ticket", { mode: "bigint" }), clientMutationId: varchar("clientMutationId", { length: 64 }), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_trades_owner_account_date_idx").on(table.userId, table.accountId, table.tradeDate), index("gj_trades_owner_account_close_idx").on(table.userId, table.accountId, table.closeTime, table.id), index("gj_trades_owner_account_result_date_idx").on(table.userId, table.accountId, table.result, table.tradeDate, table.id), uniqueIndex("gj_trades_mt5_ticket_unique").on(table.accountId, table.mt5Ticket), uniqueIndex("gj_trades_owner_account_client_mutation_unique").on(table.userId, table.accountId, table.clientMutationId), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_trades_account_owner_fk" }), check("gj_trades_direction_valid", sql`"direction" in ('BUY', 'SELL')`), check("gj_trades_result_valid", sql`"result" in ('WIN', 'LOSS', 'BREAK_EVEN', 'OPEN')`), check("gj_trades_patience_score_valid", sql`"patienceScore" is null or "patienceScore" between 1 and 5`), check("gj_trades_risk_nonnegative", sql`"risk" is null or "risk" >= 0`), check("gj_trades_reward_nonnegative", sql`"reward" is null or "reward" >= 0`)] );

export const cashMovements = pgTable("gj_cash_movements", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), movementDate: timestamp("movementDate", { withTimezone: true }).notNull(), type: varchar("type", { length: 16 }).notNull(), amount: numeric("amount", { precision: 14, scale: 2 }).notNull(), note: text("note"), clientMutationId: varchar("clientMutationId", { length: 64 }), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_cash_owner_account_idx").on(table.userId, table.accountId), index("gj_cash_owner_account_date_idx").on(table.userId, table.accountId, table.movementDate.desc()), uniqueIndex("gj_cash_owner_account_client_mutation_unique").on(table.userId, table.accountId, table.clientMutationId), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_cash_account_owner_fk" }), check("gj_cash_type_valid", sql`"type" in ('DEPOSIT', 'WITHDRAW')`), check("gj_cash_amount_positive", sql`"amount" > 0`)] );

export const goals = pgTable("gj_goals", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), description: text("description"), period: varchar("period", { length: 16 }).notNull(), metric: varchar("metric", { length: 80 }).notNull(), comparison: varchar("comparison", { length: 8 }).notNull(), target: numeric("target", { precision: 14, scale: 2 }).notNull(), notify: boolean("notify").default(true).notNull(), active: boolean("active").default(true).notNull(), isCustom: boolean("isCustom").default(false).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_goals_owner_account_idx").on(table.userId, table.accountId), index("gj_goals_owner_account_period_idx").on(table.userId, table.accountId, table.isCustom, table.period, table.createdAt), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_goals_account_owner_fk" }), check("gj_goals_period_valid", sql`"period" in ('DAILY', 'WEEKLY', 'MONTHLY')`), check("gj_goals_comparison_valid", sql`"comparison" in ('GTE', 'LTE')`)] );

export const skippedTrades = pgTable("gj_skipped_trades", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), tradeDate: timestamp("tradeDate", { withTimezone: true }).notNull(), session: varchar("session", { length: 40 }).notNull(), level: varchar("level", { length: 100 }).default(""), timeframe: varchar("timeframe", { length: 20 }).default(""), direction: varchar("direction", { length: 8 }).notNull(), skipReason: varchar("skipReason", { length: 120 }).notNull(), confidence: integer("confidence").notNull(), outcome: varchar("outcome", { length: 80 }).notNull(), estimatedMissed: numeric("estimatedMissed", { precision: 14, scale: 2 }).default("0.00").notNull(), notes: text("notes"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_skipped_owner_account_idx").on(table.userId, table.accountId), index("gj_skipped_owner_account_date_idx").on(table.userId, table.accountId, table.tradeDate.desc()), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_skipped_account_owner_fk" }), check("gj_skipped_direction_valid", sql`"direction" in ('BUY', 'SELL')`), check("gj_skipped_confidence_valid", sql`"confidence" between 1 and 5`)] );

export const dailyPlans = pgTable("gj_daily_plans", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), planDate: timestamp("planDate", { withTimezone: true }).notNull(), preBias: varchar("preBias", { length: 40 }).default(""), marketContext: text("marketContext"), keyLevels: text("keyLevels"), sessionFocus: jsonb("sessionFocus"), eventRisk: text("eventRisk"), longScenario: text("longScenario"), shortScenario: text("shortScenario"), noTradeCondition: text("noTradeCondition"), invalidationLevel: text("invalidationLevel"), riskLimit: varchar("riskLimit", { length: 40 }).default(""), maxTrades: integer("maxTrades"), sizingPlan: text("sizingPlan"), planNotes: text("planNotes"), rulesPlanned: jsonb("rulesPlanned"), emotionStart: text("emotionStart"), emotionEnd: text("emotionEnd"), executionScore: integer("executionScore"), rulesFollowed: jsonb("rulesFollowed"), whatWentWell: text("whatWentWell"), whatWentWrong: text("whatWentWrong"), executionNotes: text("executionNotes"), planDeviation: text("planDeviation"), lessons: text("lessons"), tomorrowFocus: text("tomorrowFocus"), overallRating: integer("overallRating"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_daily_plan_unique").on(table.userId, table.accountId, table.planDate), index("gj_daily_plan_owner_account_idx").on(table.userId, table.accountId), index("gj_daily_plan_owner_account_date_idx").on(table.userId, table.accountId, table.planDate.desc()), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_daily_plan_account_owner_fk" }), check("gj_daily_plan_max_trades_valid", sql`"maxTrades" is null or "maxTrades" >= 1`), check("gj_daily_plan_execution_score_valid", sql`"executionScore" is null or "executionScore" between 1 and 5`), check("gj_daily_plan_overall_rating_valid", sql`"overallRating" is null or "overallRating" between 1 and 5`)] );

export const optionLists = pgTable("gj_option_lists", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), category: varchar("category", { length: 80 }).notNull(), value: varchar("value", { length: 160 }).notNull(), active: boolean("active").default(true).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_option_list_unique").on(table.userId, table.category, table.value), index("gj_option_list_owner_idx").on(table.userId)]);

export const notificationSettings = pgTable("gj_notification_settings", { id: serial("id").primaryKey(), userId: integer("userId").notNull().unique().references(() => users.id, { onDelete: "cascade" }), goalAlerts: boolean("goalAlerts").default(true).notNull(), emailAlerts: boolean("emailAlerts").default(false).notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() });
export const aiProviderSettings = pgTable("gj_ai_provider_settings", { userId: integer("userId").primaryKey().references(() => users.id, { onDelete: "cascade" }), keyCiphertext: text("keyCiphertext").notNull(), keyIv: varchar("keyIv", { length: 32 }).notNull(), keyAuthTag: varchar("keyAuthTag", { length: 32 }).notNull(), keyFingerprint: varchar("keyFingerprint", { length: 64 }).notNull(), keyMask: varchar("keyMask", { length: 40 }).notNull(), model: varchar("model", { length: 160 }).notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() });
export const aiJobs = pgTable("gj_ai_jobs", { id: varchar("id", { length: 36 }).primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), kind: varchar("kind", { length: 24 }).notNull(), status: varchar("status", { length: 24 }).notNull(), dispatchHash: varchar("dispatchHash", { length: 64 }).notNull(), payload: jsonb("payload").notNull(), result: jsonb("result"), errorMessage: varchar("errorMessage", { length: 500 }), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(), completedAt: timestamp("completedAt", { withTimezone: true }) }, table => [index("gj_ai_jobs_owner_status_created_idx").on(table.userId, table.status, table.createdAt.desc()), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_ai_jobs_account_owner_fk" }), check("gj_ai_jobs_kind_valid", sql`"kind" in ('ANALYSIS', 'RISK_COACH')`), check("gj_ai_jobs_status_valid", sql`"status" in ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')`)]);
export const notificationHistory = pgTable("gj_notification_history", { id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").references(() => accounts.id, { onDelete: "cascade" }), type: varchar("type", { length: 60 }).notNull(), message: text("message").notNull(), readAt: timestamp("readAt", { withTimezone: true }), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => [index("gj_notification_owner_idx").on(table.userId, table.createdAt), uniqueIndex("gj_notification_user_type_unique").on(table.userId, table.type), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_notification_account_owner_fk" })]);

export const mt5Connections = pgTable("gj_mt5_connections", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), apiKey: varchar("apiKey", { length: 96 }).notNull().unique(), label: varchar("label", { length: 120 }).default("MT5 Connection").notNull(), active: boolean("active").default(true).notNull(), brokerUtcOffsetMinutes: integer("brokerUtcOffsetMinutes").default(180).notNull(), lastPing: timestamp("lastPing", { withTimezone: true }), lastContactAt: timestamp("lastContactAt", { withTimezone: true }), lastSummaryAt: timestamp("lastSummaryAt", { withTimezone: true }), lastSummarySuccessAt: timestamp("lastSummarySuccessAt", { withTimezone: true }), lastSummaryErrorAt: timestamp("lastSummaryErrorAt", { withTimezone: true }), lastOpenSyncAt: timestamp("lastOpenSyncAt", { withTimezone: true }), lastOpenSyncSuccessAt: timestamp("lastOpenSyncSuccessAt", { withTimezone: true }), lastOpenSyncErrorAt: timestamp("lastOpenSyncErrorAt", { withTimezone: true }), lastErrorAt: timestamp("lastErrorAt", { withTimezone: true }), lastErrorCode: varchar("lastErrorCode", { length: 64 }), lastErrorMessage: varchar("lastErrorMessage", { length: 255 }), consecutiveFailures: integer("consecutiveFailures").default(0).notNull(), mt5Login: bigint("mt5Login", { mode: "bigint" }), brokerServer: varchar("brokerServer", { length: 160 }), currency: varchar("currency", { length: 16 }), balance: numeric("balance", { precision: 14, scale: 2 }), equity: numeric("equity", { precision: 14, scale: 2 }), margin: numeric("margin", { precision: 14, scale: 2 }), freeMargin: numeric("freeMargin", { precision: 14, scale: 2 }), floatingPnl: numeric("floatingPnl", { precision: 14, scale: 2 }), riskSymbol: varchar("riskSymbol", { length: 32 }), riskTickSize: numeric("riskTickSize", { precision: 18, scale: 8 }), riskTickValueLoss: numeric("riskTickValueLoss", { precision: 18, scale: 8 }), riskContractSize: numeric("riskContractSize", { precision: 18, scale: 8 }), riskVolumeMin: numeric("riskVolumeMin", { precision: 18, scale: 8 }), riskVolumeMax: numeric("riskVolumeMax", { precision: 18, scale: 8 }), riskVolumeStep: numeric("riskVolumeStep", { precision: 18, scale: 8 }), riskSymbolUpdatedAt: timestamp("riskSymbolUpdatedAt", { withTimezone: true }), journalDataResetAt: timestamp("journalDataResetAt", { withTimezone: true }), lastHistorySync: timestamp("lastHistorySync", { withTimezone: true }), historySyncedCount: integer("historySyncedCount").default(0).notNull(), lastHistoryAttempt: timestamp("lastHistoryAttempt", { withTimezone: true }), lastHistoryStatus: varchar("lastHistoryStatus", { length: 32 }), lastHistoryMessage: varchar("lastHistoryMessage", { length: 255 }), lastHistoryBatchSize: integer("lastHistoryBatchSize"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_mt5_connection_account_unique").on(table.accountId), index("gj_mt5_connection_owner_idx").on(table.userId, table.accountId), index("gj_mt5_connection_health_idx").on(table.accountId, table.active, table.lastContactAt), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_mt5_connection_account_owner_fk" }), check("gj_mt5_offset_valid", sql`"brokerUtcOffsetMinutes" between -720 and 840`), check("gj_mt5_history_count_nonnegative", sql`"historySyncedCount" >= 0`), check("gj_mt5_failure_count_nonnegative", sql`"consecutiveFailures" >= 0`), check("gj_mt5_history_batch_valid", sql`"lastHistoryBatchSize" is null or "lastHistoryBatchSize" between 0 and 50`)] );

export const aiReports = pgTable("gj_ai_reports", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), analysisVersion: varchar("analysisVersion", { length: 40 }).notNull(), dataFingerprint: varchar("dataFingerprint", { length: 64 }).notNull(), model: varchar("model", { length: 160 }).notNull(), report: jsonb("report").notNull(), evidenceManifest: jsonb("evidenceManifest").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_ai_reports_id_owner_unique").on(table.id, table.userId, table.accountId), index("gj_ai_reports_owner_account_date_idx").on(table.userId, table.accountId, table.createdAt.desc()), uniqueIndex("gj_ai_reports_owner_fingerprint_unique").on(table.userId, table.accountId, table.dataFingerprint), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_ai_reports_account_owner_fk" })]);

export const aiEdgeHistory = pgTable("gj_ai_edge_history", {
  id: serial("id").primaryKey(), reportId: integer("reportId").notNull(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), evidenceId: varchar("evidenceId", { length: 24 }).notNull(), dimension: varchar("dimension", { length: 80 }).notNull(), context: varchar("context", { length: 160 }).notNull(), expectancy: numeric("expectancy", { precision: 14, scale: 6 }).notNull(), sample: integer("sample").notNull(), evidenceTier: varchar("evidenceTier", { length: 80 }).notNull(), confidence: varchar("confidence", { length: 16 }).notNull(), claimType: varchar("claimType", { length: 32 }).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_ai_edge_history_owner_account_date_idx").on(table.userId, table.accountId, table.createdAt.desc()), uniqueIndex("gj_ai_edge_history_report_evidence_unique").on(table.reportId, table.evidenceId), foreignKey({ columns: [table.reportId, table.userId, table.accountId], foreignColumns: [aiReports.id, aiReports.userId, aiReports.accountId], name: "gj_ai_edge_history_report_owner_fk" }), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_ai_edge_history_account_owner_fk" }), check("gj_ai_edge_history_sample_valid", sql`"sample" >= 0`)]);

export const aiExperimentHistory = pgTable("gj_ai_experiment_history", {
  id: serial("id").primaryKey(), reportId: integer("reportId").notNull(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), name: varchar("name", { length: 160 }).notNull(), compare: text("compare").notNull(), measure: jsonb("measure").notNull(), requiredSample: integer("requiredSample").notNull(), caution: text("caution").notNull(), status: varchar("status", { length: 24 }).default("PLANNED").notNull(), outcome: text("outcome"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_ai_experiment_history_owner_account_date_idx").on(table.userId, table.accountId, table.createdAt.desc()), uniqueIndex("gj_ai_experiment_history_report_name_unique").on(table.reportId, table.name), foreignKey({ columns: [table.reportId, table.userId, table.accountId], foreignColumns: [aiReports.id, aiReports.userId, aiReports.accountId], name: "gj_ai_experiment_history_report_owner_fk" }), foreignKey({ columns: [table.accountId, table.userId], foreignColumns: [accounts.id, accounts.userId], name: "gj_ai_experiment_history_account_owner_fk" }), check("gj_ai_experiment_history_sample_valid", sql`"requiredSample" >= 0`), check("gj_ai_experiment_history_status_valid", sql`"status" in ('PLANNED', 'RUNNING', 'COMPLETED', 'CANCELLED')`)]);

export const mt5LivePositions = pgTable("gj_mt5_live_positions", {
  id: serial("id").primaryKey(), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), ticket: bigint("ticket", { mode: "bigint" }).notNull(), symbol: varchar("symbol", { length: 32 }).notNull(), direction: varchar("direction", { length: 8 }).notNull(), lots: numeric("lots", { precision: 14, scale: 2 }).notNull(), openPrice: numeric("openPrice", { precision: 18, scale: 6 }).notNull(), closePrice: numeric("closePrice", { precision: 18, scale: 6 }), slPrice: numeric("slPrice", { precision: 18, scale: 6 }), tpPrice: numeric("tpPrice", { precision: 18, scale: 6 }), riskUsd: numeric("riskUsd", { precision: 14, scale: 2 }).default("0.00").notNull(), rewardUsd: numeric("rewardUsd", { precision: 14, scale: 2 }).default("0.00").notNull(), rrRatio: numeric("rrRatio", { precision: 14, scale: 2 }).default("0.00").notNull(), floatingPnl: numeric("floatingPnl", { precision: 14, scale: 2 }).default("0.00").notNull(), realizedPnl: numeric("realizedPnl", { precision: 14, scale: 2 }), result: varchar("result", { length: 16 }), openTime: timestamp("openTime", { withTimezone: true }).notNull(), closeTime: timestamp("closeTime", { withTimezone: true }), status: varchar("status", { length: 8 }).default("OPEN").notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_mt5_live_account_ticket_unique").on(table.accountId, table.ticket), index("gj_mt5_live_account_status_idx").on(table.accountId, table.status, table.updatedAt), index("gj_mt5_live_account_status_close_idx").on(table.accountId, table.status, table.closeTime.desc()), check("gj_mt5_position_ticket_nonnegative", sql`"ticket" >= 0`), check("gj_mt5_position_direction_valid", sql`"direction" in ('BUY', 'SELL')`), check("gj_mt5_position_status_valid", sql`"status" in ('OPEN', 'CLOSED')`), check("gj_mt5_position_lots_nonnegative", sql`"lots" >= 0`), check("gj_mt5_position_risk_nonnegative", sql`"riskUsd" >= 0`), check("gj_mt5_position_reward_nonnegative", sql`"rewardUsd" >= 0`), check("gj_mt5_position_rr_nonnegative", sql`"rrRatio" >= 0`), check("gj_mt5_position_result_valid", sql`"result" is null or "result" in ('WIN', 'LOSS', 'BREAK_EVEN', 'OPEN')`), check("gj_mt5_closed_position_complete", sql`"status" <> 'CLOSED' or ("closePrice" is not null and "closeTime" is not null and "realizedPnl" is not null and "result" is not null)`)]);

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type Account = typeof accounts.$inferSelect;
export type Trade = typeof trades.$inferSelect;
export type Goal = typeof goals.$inferSelect;
export type Mt5Connection = typeof mt5Connections.$inferSelect;
export type Mt5LivePosition = typeof mt5LivePositions.$inferSelect;
