import { bigint, boolean, integer, jsonb, numeric, pgTable, serial, text, timestamp, uniqueIndex, index, varchar } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  openId: varchar("openId", { length: 128 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: varchar("role", { length: 16 }).default("user").notNull(),
  createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn", { withTimezone: true }).defaultNow().notNull(),
});

export const accounts = pgTable("gj_accounts", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), name: varchar("name", { length: 100 }).notNull(), bootstrapKey: varchar("bootstrapKey", { length: 32 }), startingBalance: numeric("startingBalance", { precision: 14, scale: 2 }).default("0.00").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_accounts_user_idx").on(table.userId), uniqueIndex("gj_accounts_user_bootstrap_unique").on(table.userId, table.bootstrapKey)]);

export const trades = pgTable("gj_trades", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), tradeDate: timestamp("tradeDate", { withTimezone: true }).notNull(), session: varchar("session", { length: 40 }).notNull(), direction: varchar("direction", { length: 8 }).notNull(), result: varchar("result", { length: 16 }).notNull(), level: varchar("level", { length: 100 }).default(""), timeframe: varchar("timeframe", { length: 20 }).default(""), setupQuality: varchar("setupQuality", { length: 40 }).default(""), executionType: varchar("executionType", { length: 80 }).default(""), marketCondition: varchar("marketCondition", { length: 40 }).default(""), biasAlignment: varchar("biasAlignment", { length: 40 }).default(""), confirmationType: varchar("confirmationType", { length: 60 }).default(""), slPlacement: varchar("slPlacement", { length: 60 }).default(""), tpPlacement: varchar("tpPlacement", { length: 60 }).default(""), mistake: varchar("mistake", { length: 80 }).default(""), holdQuality: varchar("holdQuality", { length: 60 }).default(""), patienceScore: integer("patienceScore"), risk: numeric("risk", { precision: 14, scale: 2 }), reward: numeric("reward", { precision: 14, scale: 2 }), pnl: numeric("pnl", { precision: 14, scale: 2 }).default("0.00").notNull(), notes: text("notes"), emotionBefore: text("emotionBefore"), emotionDuring: text("emotionDuring"), emotionAfter: text("emotionAfter"), screenshotKey: varchar("screenshotKey", { length: 500 }), screenshotName: varchar("screenshotName", { length: 255 }), mt5Ticket: bigint("mt5Ticket", { mode: "bigint" }), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_trades_owner_account_date_idx").on(table.userId, table.accountId, table.tradeDate), uniqueIndex("gj_trades_mt5_ticket_unique").on(table.accountId, table.mt5Ticket)]);

export const cashMovements = pgTable("gj_cash_movements", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), movementDate: timestamp("movementDate", { withTimezone: true }).notNull(), type: varchar("type", { length: 16 }).notNull(), amount: numeric("amount", { precision: 14, scale: 2 }).notNull(), note: text("note"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_cash_owner_account_idx").on(table.userId, table.accountId)]);

export const goals = pgTable("gj_goals", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), description: text("description"), period: varchar("period", { length: 16 }).notNull(), metric: varchar("metric", { length: 80 }).notNull(), comparison: varchar("comparison", { length: 8 }).notNull(), target: numeric("target", { precision: 14, scale: 2 }).notNull(), notify: boolean("notify").default(true).notNull(), active: boolean("active").default(true).notNull(), isCustom: boolean("isCustom").default(false).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_goals_owner_account_idx").on(table.userId, table.accountId)]);

export const skippedTrades = pgTable("gj_skipped_trades", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), tradeDate: timestamp("tradeDate", { withTimezone: true }).notNull(), session: varchar("session", { length: 40 }).notNull(), level: varchar("level", { length: 100 }).default(""), timeframe: varchar("timeframe", { length: 20 }).default(""), direction: varchar("direction", { length: 8 }).notNull(), skipReason: varchar("skipReason", { length: 120 }).notNull(), confidence: integer("confidence").notNull(), outcome: varchar("outcome", { length: 80 }).notNull(), estimatedMissed: numeric("estimatedMissed", { precision: 14, scale: 2 }).default("0.00").notNull(), notes: text("notes"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [index("gj_skipped_owner_account_idx").on(table.userId, table.accountId)]);

export const dailyPlans = pgTable("gj_daily_plans", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), planDate: timestamp("planDate", { withTimezone: true }).notNull(), preBias: varchar("preBias", { length: 40 }).default(""), marketContext: text("marketContext"), keyLevels: text("keyLevels"), sessionFocus: jsonb("sessionFocus"), eventRisk: text("eventRisk"), longScenario: text("longScenario"), shortScenario: text("shortScenario"), noTradeCondition: text("noTradeCondition"), invalidationLevel: text("invalidationLevel"), riskLimit: varchar("riskLimit", { length: 40 }).default(""), maxTrades: integer("maxTrades"), sizingPlan: text("sizingPlan"), planNotes: text("planNotes"), rulesPlanned: jsonb("rulesPlanned"), emotionStart: text("emotionStart"), emotionEnd: text("emotionEnd"), executionScore: integer("executionScore"), rulesFollowed: jsonb("rulesFollowed"), whatWentWell: text("whatWentWell"), whatWentWrong: text("whatWentWrong"), executionNotes: text("executionNotes"), planDeviation: text("planDeviation"), lessons: text("lessons"), tomorrowFocus: text("tomorrowFocus"), overallRating: integer("overallRating"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_daily_plan_unique").on(table.userId, table.accountId, table.planDate), index("gj_daily_plan_owner_account_idx").on(table.userId, table.accountId)]);

export const optionLists = pgTable("gj_option_lists", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), category: varchar("category", { length: 80 }).notNull(), value: varchar("value", { length: 160 }).notNull(), active: boolean("active").default(true).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_option_list_unique").on(table.userId, table.category, table.value), index("gj_option_list_owner_idx").on(table.userId)]);

export const notificationSettings = pgTable("gj_notification_settings", { id: serial("id").primaryKey(), userId: integer("userId").notNull().unique().references(() => users.id, { onDelete: "cascade" }), goalAlerts: boolean("goalAlerts").default(true).notNull(), emailAlerts: boolean("emailAlerts").default(false).notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() });
export const notificationHistory = pgTable("gj_notification_history", { id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").references(() => accounts.id, { onDelete: "cascade" }), type: varchar("type", { length: 60 }).notNull(), message: text("message").notNull(), readAt: timestamp("readAt", { withTimezone: true }), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => [index("gj_notification_owner_idx").on(table.userId, table.createdAt)]);

export const mt5Connections = pgTable("gj_mt5_connections", {
  id: serial("id").primaryKey(), userId: integer("userId").notNull().references(() => users.id, { onDelete: "cascade" }), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), apiKey: varchar("apiKey", { length: 96 }).notNull().unique(), label: varchar("label", { length: 120 }).default("MT5 Connection").notNull(), active: boolean("active").default(true).notNull(), brokerUtcOffsetMinutes: integer("brokerUtcOffsetMinutes").default(180).notNull(), lastPing: timestamp("lastPing", { withTimezone: true }), mt5Login: bigint("mt5Login", { mode: "bigint" }), brokerServer: varchar("brokerServer", { length: 160 }), currency: varchar("currency", { length: 16 }), balance: numeric("balance", { precision: 14, scale: 2 }), equity: numeric("equity", { precision: 14, scale: 2 }), margin: numeric("margin", { precision: 14, scale: 2 }), freeMargin: numeric("freeMargin", { precision: 14, scale: 2 }), floatingPnl: numeric("floatingPnl", { precision: 14, scale: 2 }), journalDataResetAt: timestamp("journalDataResetAt", { withTimezone: true }), lastHistorySync: timestamp("lastHistorySync", { withTimezone: true }), historySyncedCount: integer("historySyncedCount").default(0).notNull(), lastHistoryAttempt: timestamp("lastHistoryAttempt", { withTimezone: true }), lastHistoryStatus: varchar("lastHistoryStatus", { length: 32 }), lastHistoryMessage: varchar("lastHistoryMessage", { length: 255 }), lastHistoryBatchSize: integer("lastHistoryBatchSize"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_mt5_connection_account_unique").on(table.accountId), index("gj_mt5_connection_owner_idx").on(table.userId, table.accountId)]);

export const mt5LivePositions = pgTable("gj_mt5_live_positions", {
  id: serial("id").primaryKey(), accountId: integer("accountId").notNull().references(() => accounts.id, { onDelete: "cascade" }), ticket: bigint("ticket", { mode: "bigint" }).notNull(), symbol: varchar("symbol", { length: 32 }).notNull(), direction: varchar("direction", { length: 8 }).notNull(), lots: numeric("lots", { precision: 14, scale: 2 }).notNull(), openPrice: numeric("openPrice", { precision: 18, scale: 6 }).notNull(), closePrice: numeric("closePrice", { precision: 18, scale: 6 }), slPrice: numeric("slPrice", { precision: 18, scale: 6 }), tpPrice: numeric("tpPrice", { precision: 18, scale: 6 }), riskUsd: numeric("riskUsd", { precision: 14, scale: 2 }).default("0.00").notNull(), rewardUsd: numeric("rewardUsd", { precision: 14, scale: 2 }).default("0.00").notNull(), rrRatio: numeric("rrRatio", { precision: 14, scale: 2 }).default("0.00").notNull(), floatingPnl: numeric("floatingPnl", { precision: 14, scale: 2 }).default("0.00").notNull(), realizedPnl: numeric("realizedPnl", { precision: 14, scale: 2 }), result: varchar("result", { length: 16 }), openTime: timestamp("openTime", { withTimezone: true }).notNull(), closeTime: timestamp("closeTime", { withTimezone: true }), status: varchar("status", { length: 8 }).default("OPEN").notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull(),
}, table => [uniqueIndex("gj_mt5_live_account_ticket_unique").on(table.accountId, table.ticket), index("gj_mt5_live_account_status_idx").on(table.accountId, table.status, table.updatedAt)]);

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type Account = typeof accounts.$inferSelect;
export type Trade = typeof trades.$inferSelect;
export type Goal = typeof goals.$inferSelect;
export type Mt5Connection = typeof mt5Connections.$inferSelect;
export type Mt5LivePosition = typeof mt5LivePositions.$inferSelect;
