import React from "react";
import { BarChart3, ShieldAlert, TrendingDown, TrendingUp } from "lucide-react";
import { formatMoney } from "@/lib/gold";
import { buildTradingEdge, EDGE_MIN_SAMPLE, type EdgeRow, type EdgeTrade } from "@/lib/tradingEdge";
import { TradingAutomationConsole } from "@/components/TradingAutomationConsole";

function EdgeTable({ title, rows }: { title: string; rows: EdgeRow[] }) {
  return <section className="edge-table-card"><header><span>{title}</span><small>{rows.length} contexts</small></header>{rows.length ? <div className="edge-table-wrap"><table><thead><tr><th>Context</th><th>Trades</th><th>Win rate</th><th>Net P&L</th><th>Expectancy</th></tr></thead><tbody>{rows.map(row => <tr key={row.key}><td><strong>{row.label}</strong>{!row.qualified && <small>Needs {EDGE_MIN_SAMPLE - row.sample} more</small>}</td><td className="data-text">{row.sample}</td><td className="data-text">{row.winRate.toFixed(0)}%</td><td className={`data-text ${row.netPnl >= 0 ? "positive" : "negative"}`}>{formatMoney(row.netPnl)}</td><td className={`data-text ${row.expectancy >= 0 ? "positive" : "negative"}`}>{formatMoney(row.expectancy)}</td></tr>)}</tbody></table></div> : <p className="edge-empty">Complete trades with these fields to evaluate this context.</p>}</section>;
}

export function AnalysisEdge({ trades }: { trades: EdgeTrade[] }) {
  const edge = buildTradingEdge(trades);
  const closed = trades.filter(trade => trade.result !== "OPEN").length;
  return <section className="analysis-edge"><div className="section-heading"><div><span className="eyebrow">ANALYSIS EDGE</span><h2>Where your strategy earns its edge</h2><p>Compare only your active account’s closed trades. Expectancy is average realized P&amp;L per trade, not a prediction.</p></div><div className="edge-sample"><BarChart3 size={17} /><span className="data-text">{closed} closed trades</span></div></div><TradingAutomationConsole trades={trades} />{closed ? <><div className="edge-callouts"><article className="edge-callout strong"><TrendingUp size={18} /><div><span>STRONGEST QUALIFIED CONTEXT</span><strong>{edge.strongest?.label ?? "Not enough evidence"}</strong><p>{edge.strongest ? `${edge.strongest.winRate.toFixed(0)}% win rate · ${formatMoney(edge.strongest.expectancy)} expectancy` : `A qualified signal needs at least ${EDGE_MIN_SAMPLE} closed trades in the same context.`}</p></div></article><article className="edge-callout weak"><TrendingDown size={18} /><div><span>WEAKEST QUALIFIED CONTEXT</span><strong>{edge.weakest?.label ?? "Not enough evidence"}</strong><p>{edge.weakest ? `${edge.weakest.winRate.toFixed(0)}% win rate · ${formatMoney(edge.weakest.expectancy)} expectancy` : "Log session, timeframe, and level consistently before changing the strategy."}</p></div></article></div><div className="edge-grid"><EdgeTable title="SESSION EDGE" rows={edge.sessions} /><EdgeTable title="TIMEFRAME EDGE" rows={edge.timeframes} /><EdgeTable title="LEVEL EDGE" rows={edge.levels} /></div><div className="edge-grid edge-grid-combos"><EdgeTable title="SESSION × TIMEFRAME" rows={edge.sessionTimeframes} /><EdgeTable title="LEVEL × SESSION" rows={edge.levelSessions} /><EdgeTable title="LEVEL × TIMEFRAME" rows={edge.levelTimeframes} /></div></> : <div className="edge-guidance"><ShieldAlert size={19} /><div><strong>No closed trades to evaluate yet.</strong><p>For useful edge evidence, record at least {EDGE_MIN_SAMPLE} closed trades in each context and avoid making strategy changes from one or two outcomes.</p></div></div>}</section>;
}
