import React, { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Search, TrendingDown, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatMoney } from "@/lib/gold";
import { monthKeys, monthlyOverview } from "@/lib/performanceSummary";

function monthLabel(key: string, style: "long" | "short" = "short") { return new Date(`${key}-01T12:00:00`).toLocaleString("en-US", { month: style, year: "numeric" }); }

export function MonthlyTradeOverview({ trades, selectedMonth, onMonthChange }: { trades: any[]; selectedMonth?: string; onMonthChange?: (month: string) => void }) {
  const keys = useMemo(() => monthKeys(trades), [trades]); const [query, setQuery] = useState(""); const [pickerOpen, setPickerOpen] = useState(false); const [internalSelected, setInternalSelected] = useState(keys[0]); const selected = selectedMonth ?? internalSelected;
  const availableKeys = useMemo(() => Array.from(new Set([selected, ...keys])).filter(Boolean), [keys, selected]); const visibleKeys = useMemo(() => availableKeys.filter(key => monthLabel(key, "long").toLowerCase().includes(query.trim().toLowerCase())), [availableKeys, query]);
  const choose = (month: string) => { if (!selectedMonth) setInternalSelected(month); onMonthChange?.(month); };
  useEffect(() => { if (visibleKeys.length && !visibleKeys.includes(selected)) choose(visibleKeys[0]); }, [visibleKeys, selected]); const summary = monthlyOverview(trades, selected); const label = monthLabel(selected, "long"); const selectedIndex = availableKeys.indexOf(selected); const move = (offset: number) => { const next = availableKeys[selectedIndex - offset]; if (next) choose(next); };
  return <section className="monthly-trade-overview"><div className="monthly-overview-head"><div><span className="eyebrow">MONTHLY PERFORMANCE</span><h3>{label} overview</h3><p>Search and choose a month to review trade volume, win/loss behavior, P&amp;L, and average planned R:R before reviewing the calendar rhythm.</p></div><div className="monthly-month-picker"><label className="monthly-search"><Search size={14} /><span className="sr-only">Search overview month</span><input aria-label="Search overview month" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search month" /></label><div className="monthly-theme-picker"><Button type="button" variant="outline" size="icon" aria-label="Previous overview month" disabled={selectedIndex >= availableKeys.length - 1} onClick={() => move(-1)}><ChevronLeft size={15} /></Button><Button type="button" variant="outline" className="month-picker-trigger" aria-haspopup="listbox" aria-expanded={pickerOpen} onClick={() => setPickerOpen(open => !open)}><CalendarDays size={15} /> {label}</Button><Button type="button" variant="outline" size="icon" aria-label="Next overview month" disabled={selectedIndex <= 0} onClick={() => move(1)}><ChevronRight size={15} /></Button>{pickerOpen && <div className="monthly-theme-options" role="listbox" aria-label="Overview month">{visibleKeys.length ? visibleKeys.map(key => <button type="button" role="option" aria-selected={key === selected} className={key === selected ? "selected" : ""} key={key} onClick={() => { choose(key); setPickerOpen(false); }}>{monthLabel(key)}</button>) : <p>No matching month</p>}</div>}</div></div></div><div className="monthly-metric-grid"><div><span>Trades</span><strong className="data-text">{summary.trades}</strong><small>{summary.open} open · {summary.breakEven} break-even</small></div><div><span>Wins / losses</span><strong className="data-text">{summary.wins} / {summary.losses}</strong><small>{summary.closed} closed trades</small></div><div><span>Win rate</span><strong className="data-text">{summary.winRate.toFixed(1)}%</strong><small>{summary.wins ? <><TrendingUp size={12} /> Winning executions</> : "No closed wins yet"}</small></div><div className={summary.pnl >= 0 ? "good" : "bad"}><span>Net P&amp;L</span><strong className="data-text">{formatMoney(summary.pnl)}</strong><small>{summary.pnl >= 0 ? <><TrendingUp size={12} /> Month to date</> : <><TrendingDown size={12} /> Month to date</>}</small></div><div><span>Average planned R:R</span><strong className="data-text">1 : {summary.avgRr.toFixed(2)}</strong><small>Risk-defined trades only</small></div></div></section>;
}
