create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create or replace function public.owns_account(target uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.trading_accounts where id = target and owner_id = auth.uid() and is_archived = false); $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, avatar_preference text default 'initials', theme_preference text not null default 'dark' check(theme_preference in ('dark','light')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.trading_accounts (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null check(length(name) between 1 and 120), broker_name text, base_currency text not null default 'USD', starting_balance numeric, is_active boolean not null default true, is_archived boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.trades (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, trade_at_utc timestamptz not null, pkt_session text not null, source text not null default 'manual' check(source in ('manual','mt5')), mt5_ticket bigint, direction text check(direction in ('Long','Short')), result text check(result in ('Win','Loss','Breakeven','Open')), risk_usd numeric check(risk_usd is null or risk_usd > 0), planned_reward_usd numeric check(planned_reward_usd is null or planned_reward_usd >= 0), realized_pnl numeric, bias text, level text, timeframe text, setup_quality text, execution_type text, market_condition text, confirmation_type text, sl_placement text, tp_placement text, behavior_tags text[] not null default '{}', hold_quality smallint check(hold_quality between 1 and 5), patience_score smallint check(patience_score between 1 and 5), emotion_before text, emotion_during text, emotion_after text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(account_id, mt5_ticket));
create table if not exists public.trade_screenshots (id uuid primary key default gen_random_uuid(), trade_id uuid not null references public.trades(id) on delete cascade, account_id uuid not null references public.trading_accounts(id) on delete cascade, object_path text not null unique, display_order integer not null default 0, original_filename text not null, mime_type text not null check(mime_type in ('image/jpeg','image/png','image/webp')), created_at timestamptz not null default now());
create table if not exists public.mt5_connections (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, terminal_label text not null, status text not null default 'pending' check(status in ('pending','connected','stale','error')), last_seen timestamptz, broker_balance numeric, broker_equity numeric, floating_pnl numeric, api_key_verifier text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.mt5_positions (id uuid primary key default gen_random_uuid(), connection_id uuid not null references public.mt5_connections(id) on delete cascade, account_id uuid not null references public.trading_accounts(id) on delete cascade, mt5_position_ticket bigint not null, opened_at_utc timestamptz, closed_at_utc timestamptz, direction text check(direction in ('Long','Short')), status text not null check(status in ('open','closed')), risk_usd numeric, planned_reward_usd numeric, realized_pnl numeric, payload_hash text, reconciled_trade_id uuid references public.trades(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(account_id, mt5_position_ticket));
create table if not exists public.cash_movements (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, movement_type text not null check(movement_type in ('deposit','withdrawal')), amount numeric not null check(amount > 0), note text, moved_at timestamptz not null default now());
create table if not exists public.trader_goals (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, title text not null, is_active boolean not null default true, period text not null check(period in ('daily','weekly','monthly')), metric text not null check(metric in ('realized_pnl','loss_streak','trade_count','rule_violations','fomo_tags','revenge_tags','screenshot_rate','plan_completion')), comparator text not null check(comparator in ('at_most','at_least')), target numeric not null, strategy_scope text, notification_enabled boolean not null default true, template_key text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.goal_alerts (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, goal_id uuid not null references public.trader_goals(id) on delete cascade, period_key text not null, status text not null, message text not null, is_read boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(goal_id, period_key));
create table if not exists public.skipped_trades (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, skipped_at timestamptz not null, pkt_session text not null, direction text check(direction in ('Long','Short')), reason text, confidence text, later_outcome text check(later_outcome in ('Win','Loss','Breakeven','Open')), estimated_missed_pnl numeric, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.daily_plans (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, plan_date date not null, pre_market_plan text, thesis text, key_levels text, scenarios text, invalidation text, news_context text, risk_limits text, selected_rules text[] not null default '{}', execution_checklist jsonb not null default '{}', post_session_score smallint check(post_session_score between 1 and 10), review_notes text, is_archived boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(account_id, plan_date));
create table if not exists public.option_lists (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, category text not null, label text not null, enabled boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(account_id, category, label));
create table if not exists public.trading_rules (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, title text not null, is_active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, category text not null, title text not null, body text not null, is_read boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.mentor_reports (id uuid primary key default gen_random_uuid(), account_id uuid not null references public.trading_accounts(id) on delete cascade, date_from date not null, date_to date not null, prompt_summary text not null, result text not null, model_metadata jsonb not null default '{}', created_at timestamptz not null default now());

create index if not exists trades_account_date_idx on public.trades(account_id, trade_at_utc desc); create index if not exists trades_account_result_idx on public.trades(account_id, result); create index if not exists plans_account_date_idx on public.daily_plans(account_id, plan_date desc); create index if not exists skipped_account_date_idx on public.skipped_trades(account_id, skipped_at desc); create index if not exists notifications_account_read_idx on public.notifications(account_id, is_read, created_at desc);

do $$ declare t text; begin foreach t in array array['profiles','trading_accounts','trades','trade_screenshots','mt5_connections','mt5_positions','cash_movements','trader_goals','goal_alerts','skipped_trades','daily_plans','option_lists','trading_rules','notifications','mentor_reports'] loop execute format('alter table public.%I enable row level security', t); end loop; end $$;

create policy "profile owner" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "account owner" on public.trading_accounts for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
do $$ declare t text; begin foreach t in array array['trades','trade_screenshots','mt5_connections','mt5_positions','cash_movements','trader_goals','goal_alerts','skipped_trades','daily_plans','option_lists','trading_rules','notifications','mentor_reports'] loop execute format('create policy "account scoped owner" on public.%I for all using (public.owns_account(account_id)) with check (public.owns_account(account_id));', t); end loop; end $$;

insert into storage.buckets(id,name,public) values ('trade-screenshots','trade-screenshots',false) on conflict (id) do nothing;
create policy "private screenshot owner" on storage.objects for all using (bucket_id = 'trade-screenshots' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'trade-screenshots' and (storage.foldername(name))[1] = auth.uid()::text);

do $$ declare t text; begin foreach t in array array['trades','trade_screenshots','mt5_connections','mt5_positions','cash_movements','trader_goals','goal_alerts','skipped_trades','daily_plans','option_lists','trading_rules','notifications','mentor_reports'] loop execute format('drop trigger if exists set_updated_at on public.%I', t); execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', t); end loop; end $$;
